<div class="ny6_1">
    <div class="m9">
    <img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" width="310" height="425" />
    <a href="[field:arcurl/]" title="[field:fulltitle function='htmlspecialchars(@me)'/]"><img src="/images1/d04.png" /></a>
    </div>
    <h2><a href="[field:arcurl/]" title="[field:fulltitle function='htmlspecialchars(@me)'/]">[field:title/]</a></h2>
    <div class="m10">POST TIME:[field:pubdate function="MyDate('Y/m/d',@me)"/]</div>
  </div>