<?php
$z[0]=Array("litpic","",57,72);
$z[1]=Array("title","",79,119);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("arcurl","",163,178);
$z[3]=Array("fulltitle","",187,238);
$z[3][4]['function']="htmlspecialchars(@me)";
$z[4]=Array("arcurl","",305,320);
$z[5]=Array("fulltitle","",329,380);
$z[5][4]['function']="htmlspecialchars(@me)";
$z[6]=Array("title","",382,396);
$z[7]=Array("pubdate","",438,485);
$z[7][4]['function']="MyDate('Y/m/d',@me)";

?>