<div class="k5_1">
    <div class="m1">
      <div class="m1_1">[field:pubdate function="MyDate('Y',@me)"/]</div>
      <div class="m1_2">[field:pubdate function="MyDate('m.d',@me)"/]</div>
    </div>
    <div class="m2"><a href="[field:arcurl/]" title="[field:fulltitle function='htmlspecialchars(@me)'/]"><img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" width="121" height="88" /></a></div>
    <div class="m3">
      <h2><a href="[field:arcurl/]" title="[field:fulltitle function='htmlspecialchars(@me)'/]">[field:title/]</a></h2>
      <p>[field:infos/]...</p>
      <div class="m3_1"><a href="[field:arcurl/]">点击了解更多</a></div>
    </div>
  </div>