<div class="e4">
    <div class="pic"><a href="[field:arcurl/]" title="[field:fulltitle/]"><img src="[field:litpic/]" alt="[field:fulltitle/]" /></a></div>
    <div class="e4_1">
    <div class="sj">posttime:[field:pubdate function="MyDate('Y/m/d',@me)"/]</div>
    <h3><a href="[field:arcurl/]" title="[field:fulltitle/]">[field:title/]</a></h3>
    <p><a href="[field:arcurl/]">[field:info/]...</a></p>
    </div>
  </div>