<?php
$z[0]=Array("channel","\r\n	<li class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-237\" id=\"menu-item-237\"><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n	",2968,3183);
$z[0][4]['typeid']="2";
$z[0][4]['type']="son";
$z[1]=Array("global","",3851,3878);
$z[1][4]['name']="dede_powerby";
$z[2]=Array("flink","\r\n    <li>[field:link /]</li>\r\n	",4039,4128);
$z[2][4]['row']="30";
$z[2][4]['type']="text";
$z[2][4]['typeid']="1";

?>