<?php
$z[0]=Array("field","if(@me=='1')@me='<li id=\"menu-item-50\" class=\"menu-item menu-item-type-post_type current-menu-item menu-item-object-page menu-item-has-children menu-item-50\">';else@me='<li id=\"menu-item-50\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-50\">';",409,780);
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[0][4]['function']="GetTopid(@me)";
$z[1]=Array("channel","\r\n	  <li id=\"menu-item-51\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-51\"><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n	  ",841,1055);
$z[1][4]['typeid']="1";
$z[1][4]['type']="son";
$z[2]=Array("field","if(@me=='2')@me='<li id=\"menu-item-47\" class=\"menu-item menu-item-type-taxonomy current-menu-item menu-item-object-category menu-item-has-children menu-item-47\">';else@me='<li id=\"menu-item-47\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-47\">';",1076,1453);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[2][4]['function']="GetTopid(@me)";
$z[3]=Array("channel","\r\n	  <li id=\"menu-item-48\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-48\"><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n	  ",1513,1730);
$z[3][4]['typeid']="2";
$z[3][4]['type']="son";
$z[4]=Array("field","if(@me=='3')@me='<li id=\"menu-item-47\" class=\"menu-item menu-item-type-taxonomy current-menu-item menu-item-object-category menu-item-has-children menu-item-47\">';else@me='<li id=\"menu-item-47\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-47\">';",1754,2131);
$z[4][4]['name']="typeid";
$z[4][4]['runphp']="yes";
$z[4][4]['function']="GetTopid(@me)";
$z[5]=Array("channel","\r\n	  <li id=\"menu-item-48\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-48\"><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n	  ",2191,2408);
$z[5][4]['typeid']="3";
$z[5][4]['type']="son";
$z[6]=Array("field","if(@me=='4')@me='<li id=\"menu-item-47\" class=\"menu-item menu-item-type-taxonomy current-menu-item menu-item-object-category menu-item-has-children menu-item-47\">';else@me='<li id=\"menu-item-47\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-47\">';",2432,2809);
$z[6][4]['name']="typeid";
$z[6][4]['runphp']="yes";
$z[6][4]['function']="GetTopid(@me)";
$z[7]=Array("field","if(@me=='5')@me='<li id=\"menu-item-46\" class=\"menu-item menu-item-type-taxonomy current-menu-item menu-item-object-category menu-item-has-children menu-item-46\">';else@me='<li id=\"menu-item-46\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-46\">';",2846,3223);
$z[7][4]['name']="typeid";
$z[7][4]['runphp']="yes";
$z[7][4]['function']="GetTopid(@me)";
$z[8]=Array("channel","\r\n	  <li id=\"menu-item-53\" class=\"menu-item menu-item-type-custom menu-item-object-custom menu-item-53\"><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n	  ",3283,3496);
$z[8][4]['typeid']="5";
$z[8][4]['type']="son";
$z[9]=Array("field","if(@me=='6')@me='<li id=\"menu-item-52\" class=\"menu-item menu-item-type-post_type current-menu-item menu-item-object-page menu-item-52\">';else@me='<li id=\"menu-item-52\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-52\">';",3517,3842);
$z[9][4]['name']="typeid";
$z[9][4]['runphp']="yes";
$z[9][4]['function']="GetTopid(@me)";

?>