<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.hdqx' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.hdqx
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (11) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,3 </font>
Time2015-04-24 15:29:48
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.hdqx' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.hdqx
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (11) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,3 </font>
Time2015-04-24 15:29:53
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'addf.hdqx' in 'field list' <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.hdqx
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `dede_addonarticle` addf ON addf.aid = arc.id 
         WHERE  arc.typeid IN (11) And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,3 </font>
Time2015-11-15 20:56:10
*/
?>
